name = "keyan-m/aiken-scott-utils"
version = "v1.4.0"
compiler = "v1.1.19"
plutus = "v3"
license = "Apache-2.0"
description = "A set of utility functions that return multiple values in Scott encoding rather than tuples of 2 or higher"

[repository]
user = "keyan-m"
project = "aiken-scott-utils"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[config]
